spring:
  application:
    name: abada
  datasource:
    url: jdbc:h2:mem:abada;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


server:
  port: 5601

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: this-is-a-long-and-secure-jwt-secret-key-256-bit

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG