spring:
  application:
    name: abada
  datasource:
    url: jdbc:h2:mem:abada;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


server:
  port: 5601
