# OpenTelemetry Configuration
management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
    metrics:
      endpoint: http://localhost:4318/v1/metrics
  tracing:
    sampling:
      probability: 1.0  # 100% sampling in development, adjust for production
    baggage:
      enabled: true
    propagation:
      type: W3C
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        abada.process.duration: true
        abada.task.waiting_time: true
        abada.task.processing_time: true
        abada.job.execution_time: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
        abada.process.duration: 0.5, 0.95, 0.99
        abada.task.waiting_time: 0.5, 0.95, 0.99
        abada.task.processing_time: 0.5, 0.95, 0.99
        abada.job.execution_time: 0.5, 0.95, 0.99
    export:
      otlp:
        enabled: true
        step: 10s
        url: ${management.otlp.metrics.endpoint}

# Application Information
app:
  version: ${APP_VERSION:0.8.2-alpha}

spring:
  application:
    name: abada-engine

# Logging Configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    com.abada.engine: DEBUG
    io.opentelemetry: INFO
    io.micrometer: INFO

# OpenTelemetry Resource Attributes
otel:
  resource:
    attributes:
      deployment.environment: ${OTEL_DEPLOYMENT_ENVIRONMENT:development}
      service.namespace: com.abada
      service.name: ${spring.application.name}
      service.version: ${app.version}
      service.instance.id: ${HOSTNAME:unknown}

# OpenTelemetry Batch Export Configuration
otel.traces.exporter:
  otlp:
    timeout: 30s
  batch:
    max.queue.size: 2048
    max.export.batch.size: 512
    schedule.delay: 5s