spring:
  application:
    name: abada-engine-${spring.profiles.active}

  datasource:
      url: jdbc:h2:file:./data/abada-dev-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password: ${DB_PASSWORD:abada123}
  jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
      console:
        enabled: true
        path: /h2-console

# OpenTelemetry Development Configuration
management:
  tracing:
    sampling:
      probability: 1.0  # Always sample in development
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
    metrics:
      endpoint: http://localhost:4318/v1/metrics

otel:
  resource:
    attributes:
      deployment.environment: dev
  traces:
    sampler.arg: 1.0  # Always sample

logging:
  level:
    org.springframework.web: TRACE
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.zaxxer.hikari: DEBUG
    io.opentelemetry: DEBUG
    io.micrometer: DEBUG
    com.abada.engine: DEBUG
